{% set name = "libssh2" %}
{% set version = "1.8.0" %}
{% set sha256 = "39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.libssh2.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true   # [win and py36]
  features:
      - vc9    # [win and py27]
      - vc10   # [win and py34]
      - vc14   # [win and (py35 or py36)]

requirements:
  build:
    - python         # [win]
    - cmake >2.8
    - openssl 1.0.*
    - toolchain
    - zlib 1.2.8
    # cmake->curl(7.54.1)->libssh2 brings in a cyclic dep
    # 7.52.1 version of curl doesn't depend on libssh2
    - curl 7.52.*
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and (py35 or py36)]
  run:
    - openssl 1.0.*
    - zlib 1.2.8
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and (py35 or py36)]

test:
  commands:
    - test -f $PREFIX/include/libssh2.h              # [not win]
    - test -f $PREFIX/include/libssh2_publickey.h    # [not win]
    - test -f $PREFIX/include/libssh2_sftp.h         # [not win]
    
    - test -f $PREFIX/lib/libssh2.a                  # [not win]
    - test -f $PREFIX/lib/libssh2.so                 # [linux]
    - test -f $PREFIX/lib/libssh2.dylib              # [osx]

    - if not exist %LIBRARY_INC%\\libssh2.h           exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libssh2_sftp.h      exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libssh2.lib         exit 1  # [win]


about:
  home: https://www.libssh2.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'the SSH library'

  description: |
    libssh2 is a library implementing the SSH2 protocol, available under the revised BSD license.
  dev_url: https://github.com/libssh2/libssh2

extra:
  recipe-maintainers:
    - shadowwalkersb
    - nehaljwani
    - ocefpaf
