appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: ts4Zgr7UOPJ2jLDtuYnfQrPZYjugKtwD0Bzk17X8sr16YiudyZhtv+MqujM9KKXXA1mPEEJcLVLDWJtTdABkwmqEZ+GhNm04c9AWeoaI72OT6XFP0wQk/qtLqJggr9oeUBrisxMGxX7YW8pOBucoskpj6bJ6w+mDMDZAzo7IQrlVixgDJBCecGt76uKKR/WdZ7lMIwM2XRflavCwzNRWZNUBHJvSKVeST0XjbTpWQHrmWvpq94uu4XXeEarXBWoP6Iq6IuSfH/pL8xfuE6m0rLHmTvc4rIZoYE2aJhAFQq1CgAi1dM5OMHuYTF8LJck/3gOAFUqg6YO2jvcgzIQO3fNfwNciLyX3bQezEeZ9EPJPlqAAby8PYw5cT9nkm63HHX0REQhAoxTAS+iVvNeRjaH1B4yInLiSSOapnL+AHeqqDyAzXzchrUil2ECCYh+fo6YDCruy+Kd4ASjP2Y+GNgX5uOqSO+qv58UQjcJOMir1xkgspYoNWLSCHdCK7Plf4HIJXQpjTh/NTiIhVBCpXAfkZYo3vtw3W36C5DMU/z985IWHqJw8F0C/Q6wk2lU9YJZLHWLfaqYB5AI/+ziN9ZFseSs7niKg3Kc91yeR6/+2qAU1utxyO7vSWVKvX1x0JUe2FzNBDTBIMnChvxESkeGPN2sbo0c6r5KoqvZXvZE=}
